# src/config.py

CATEGORY_LABELS = {
    "models": "Modelos",
    "infra": "Infraestructura/HW",
    "invest": "Economía/mercado",
    "geopol": "Geopolítica",
    "policy": "Política/Regulación",
    "security": "Seguridad",
    "research": "Investigación",
    "products": "Producto",
    "chips": "Chips",
    "robotics": "Robótica",
    "compute": "Computación",
    "misc": "Otros",
}

KNOWN_ENTITIES = [
    "OpenAI", "NVIDIA", "Anthropic", "Google", "DeepMind", "Microsoft", "Meta", "Apple",
    "Amazon", "AWS", "Azure", "TSMC", "AMD", "Intel", "Arm", "Tesla",
    "Cerebras", "Groq", "Mistral", "Hugging Face", "Stability AI",
    "ByteDance", "Alibaba", "Tencent", "Samsung", "Qualcomm", "xAI", "DeepSeek",
    "Gemini 3.5", "Gemini 3", "Gemini", "Claude 3.7", "Claude 3.5", "Claude",
    "GPT-5.5", "GPT-5", "GPT-4.5", "o1", "o3", "o4", "ChatGPT", "Grok 3", "Grok",
    "DeepSeek-R1", "DeepSeek-V3", "Kimi K3", "Kimi", "Moonshot AI",
    "GLM-5", "GLM-4", "GLM", "Zhipu AI", "Qwen 2.5", "Qwen 3", "Qwen",
    "Llama 4", "Llama 3.3", "Llama", "Mistral Large", "Codestral",
    "Fable", "Mythos", "Sol", "MiniMax", "01.AI", "Yi", "Baichuan",
    "Cohere", "Scale AI", "Together AI", "ASML", "SMIC", "Blackwell",
    "Huawei", "Baidu", "CoreWeave", "SoftBank", "Oracle", "Broadcom", "SK hynix",
]

ENTITY_ALIASES = {
    "UK": "Reino Unido",
    "US": "EEUU",
    "USA": "EEUU",
    "EU": "UE",
    "Google DeepMind": "DeepMind",
    "OpenAIDevs": "OpenAI",
    "OpenAI Developers": "OpenAI",
    "Nvidia": "NVIDIA",
    "Xai": "xAI",
    "Kimi k3": "Kimi K3",
    "Kimi-K3": "Kimi K3",
    "Moonshot": "Moonshot AI",
    "MoonshotAI": "Moonshot AI",
    "Zhipu": "Zhipu AI",
    "ZhipuAI": "Zhipu AI",
    "GLM 5": "GLM-5",
    "GLM5": "GLM-5",
    "GLM-5.3": "GLM-5",
    "GLM 4": "GLM-4",
    "Qwen2.5": "Qwen 2.5",
    "Qwen3": "Qwen 3",
    "Alibaba Qwen": "Qwen",
    "DeepSeek-R1": "DeepSeek-R1",
    "DeepSeek-V3": "DeepSeek-V3",
    "Deepseek": "DeepSeek",
    "Claude 3.7": "Claude 3.7",
    "Claude 3.5": "Claude 3.5",
    "Gemini 3.5": "Gemini 3.5",
    "Gemini 3": "Gemini 3",
    "GPT-5": "GPT-5",
    "GPT-5.5": "GPT-5.5",
    "Fable Studio": "Fable",
    "Mythos AI": "Mythos",
    "Sol AI": "Sol",
}

STOP_ENTITIES = {
    "AI", "ML", "LLM", "RAG", "RL", "GPU", "CPU", "API", "SDK", "OSS", "PDF", "HTML",
    "Update", "Quote", "Thread", "Post", "Tweet", "Image", "Video", "New", "Apr", "May",
    "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar", "CEO", "CTO",
    "Our", "The", "This", "That", "Today", "Tomorrow", "Project", "Research", "Blog",
    "Pro", "Developers", "Resources", "Link", "Read", "More", "Welcome", "Live",
    "His", "Her", "Their", "Introducing", "Interview", "CEO Interview",
    "You", "Paul", "Misc", "Stop", "Making", "Stop Making", "Best", "Top", "Great",
    "Use", "Simulate", "Science", "Premium", "Regulation",
    "General Data Protection", "Introducing Gemini Omni", "TUIs", "TUI", "CLI", "CLIs",
    "Neoclouds", "Neocloud", "Guide", "Ranking", "Ranked", "Review", "Summary", "Overview",
    "How", "Why", "What", "When", "Where", "Build", "Building", "Run", "Running",
}
ALLOW_ACRONYMS = {"AWS", "TSMC", "AMD", "ARM", "NVIDIA", "GPT", "CUDA", "EEUU", "UE", "xAI", "GLM", "SMIC", "ASML", "MCP"}
